version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: compose/production/web/Dockerfile
    container_name: sena_landing_production
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: always
