import architecture from "@/public/icons/architecture.svg";
import close from "@/public/icons/close.svg";
import dangerToast from "@/public/icons/danger-toast.svg";
import facebook from "@/public/icons/facebook.svg";
import instagram from "@/public/icons/instagram.svg";
import linkedin from "@/public/icons/linkedin.svg";
import menu from "@/public/icons/menu.svg";
import monitoring from "@/public/icons/monitoring.svg";
import nodes from "@/public/icons/nodes.svg";
import plus from "@/public/icons/plus.svg";
import rings from "@/public/icons/rings.svg";
import successToast from "@/public/icons/success-toast.svg";
import xMark from "@/public/icons/x-mark.svg";
import youtube from "@/public/icons/youtube.svg";

export class AssetIcon {
  static facebook = facebook;
  static instagram = instagram;
  static linkedin = linkedin;
  static youtube = youtube;
  static menu = menu;
  static xMark = xMark;
  static rings = rings;
  static nodes = nodes;
  static monitoring = monitoring;
  static architecture = architecture;
  static plus = plus;
  static close = close;
  static dangerToast = dangerToast;
  static successToast = successToast;
}
