import aomLogo from '@/public/images/aom_logo.png'
import aquariusConsultingLogo from '@/public/images/aquarius_consulting_logo.png'
import autogestion from '@/public/images/autogestion.png'
import byRecsa from '@/public/images/byRecsa.png'
import cientificaLogo from '@/public/images/cientifica_logo.png'
import cobra from '@/public/images/cobra.png'
import conciliator1 from '@/public/images/conciliator1.png'
import conciliatorNavbar from '@/public/images/conciliator_navbar.jpg'
import contactanos1 from '@/public/images/contactanos1.png'
import evalua from '@/public/images/evalua.png'
import home1 from '@/public/images/home1.png'
import home2 from '@/public/images/home2.png'
import home3 from '@/public/images/home3.png'
import home4 from '@/public/images/home4.png'
import logoBlack from '@/public/images/logo_black.png'
import logoBlanco from '@/public/images/logo_blanco.png'
import mapLatamRecsa from '@/public/images/mapLatamRecsa.png'
import maruzLogo from '@/public/images/maruz_logo.png'
import nosotros1 from '@/public/images/nosotros1.png'
import nosotros2 from '@/public/images/nosotros2.png'
import proweldLogo from '@/public/images/proweld_logo.png'
import recuperaGirl from '@/public/images/recupera_girl.jpeg'
import rioSena from '@/public/images/rio_sena.jpg'
import senaLogoOrange from '@/public/images/sena_logo_orange.png'
import sincroniza from '@/public/images/sincroniza.png'
import telefonicaLogo from '@/public/images/telefonica_logo.png'
import topSpaceLogo from '@/public/images/top_space_logo.png'

export class AssetImage {
  static logoBlack = logoBlack
  static home1 = home1
  static home2 = home2
  static nosotros1 = nosotros1
  static rioSena = rioSena
  static senaLogoOrange = senaLogoOrange
  static conciliator1 = conciliator1
  static conciliatorNavbar = conciliatorNavbar
  static cientificaLogo = cientificaLogo
  static proweldLogo = proweldLogo
  static aquariusConsultingLogo = aquariusConsultingLogo
  static telefonicaLogo = telefonicaLogo
  static maruzLogo = maruzLogo
  static aomLogo = aomLogo
  static topSpaceLogo = topSpaceLogo
  static home3 = home3
  static logoBlanco = logoBlanco
  static nosotros2 = nosotros2
  static home4 = home4
  static sincroniza = sincroniza
  static contactanos1 = contactanos1
  static cobra = cobra
  static evalua = evalua
  static autogestion = autogestion
  static recuperaGirl = recuperaGirl
  static byRecsa = byRecsa
  static mapLatamRecsa = mapLatamRecsa
}
